# Syllabus


**Instructor**: Joshua Jackson  
**Office**: 315B  
**Office hours**: 10-11 Wednesday and by appointment  

**Course Descrition** 

This course covers modern methods of handling longitudinal, repeated measures. The class will introduce the rationale of measuring change and stability over time to study phenomena, as well as how within-person designs can increase statistical power and precision compared to more traditional designs. Most the course will use multi-level models and latent (growth) curve models to specify patterns of change across time. Additional topics include: visualization, measurement invariance, time-to- event models and power. PREREQ: Use of R will be required, Familiarity with MLM and/or Structural Equation Models.

**Class textbook** 

Readings will be provided

**Structure of class**

Each class will cover a specific type of longitudinal model. During that class, I (josh) will provide an overview of the important considerations or motivation for this analysis. Then we will switch to walking through code and results. For each topic I will select (in advance) someone who will meet with me outside of class time to go over analyses for that topic using their own dataset. That person will be in charge of providing background information on the dataset and discussing the progress of their data analytic plan. Final code will be shared to the class via Github. 

If you are not presenting you will need to run the analyses using your own dataset or one that is appropriate for the techinique. These are due before the start of the next class.  

**Grading** 
Grading consists of 3 aspects: 
1. Weekly projects uploaded to github (60% of grade)
2. Class presentation based on your data (20%)
3. Final paper covering the method and results of your main longitudinal hypothesis(es) (20%)

**Schedule**

| Week | Date  |  Topic                                                     | Readings             |
-------|-------|------------------------------------------------------------|----------------------|
| 1    | 8/31  | Motivation, terms, concepts and graphing                                 |                      |
| 2    | 9/7  | Growth curves; MLM in R: packages and procedures       |                      |
| 3    | 9/14   |  Conditional (Leve 1 and 2 predictors) MLM models     |                      |
| 4    | 9/21   |  **Class canceled**                   |        |
| 5    | 9/28  |  Polynomial, piecewise and spline models   |                      |
| 6    | 10/05  | Intensive data anlysis/within person fluctuations p1  |                      |
| 7    | 10/12  | Intensive data anlysis/within person fluctuations p2   |                      |
| 8    | 10/19   |   Bayesian estimation                             |                      |
| 9    | 10/26  |    SEM and Latent Grown (curve) Models                  |                      |
| 10   | 11/2  |  Scaling, MI, and Second order Model                      |                      |
| 11   | 11/9  |   Multiple group models               |                      |
| 12   | 11/16   |  Dyadic Models                        |                      |
| 13   | 11/23  |  **Tofurkey day**            |                      |
| 14   | 11/30  |  Flexible SEM models (LCM, STATE-TRAIT; ALT-SR)                                     |                      |
| 15   | 12/7  |  Mixture Models   |                      |

Other topics: Longitudinal mediation (and multilevel mediation), two wave data, experimental approaches 
