# Conditional Predictors in growth models



## Intercept effects
level 1: 
$$ {Y}_{ij} = \beta_{0j}  + \beta_{1j}Time_{ij} + \varepsilon_{ij} $$
Level 2: 
$$ {\beta}_{0j} = \gamma_{00} + \gamma_{01}G_{j} +   U_{0j}$$  
$$ {\beta}_{1j} = \gamma_{10} + U_{1j} $$  



Combined
  $$ {Y}_{ij} = \gamma_{00} + \gamma_{01}G_{j}+  \gamma_{10} (Time_{ij}) + U_{0j} + U_{1j}(Time_{ij}) + \varepsilon_{ij} $$

$$ \begin{pmatrix} {U}_{0j} \\ {U}_{1j} \end{pmatrix}
\sim \mathcal{N} \begin{pmatrix} 
  0,     & \tau_{00}^{2} & \tau_{01}\\ 
  0, & \tau_{01} & \tau_{10}^{2}
\end{pmatrix} $$


$$ {R}_{ij} \sim \mathcal{N}(0, \sigma^{2})  $$


### Seperatinng these into intercept and slope

  $$ {Y}_{ij} = [\gamma_{00} + \gamma_{01}G_{j}+ U_{0j}]  + [(\gamma_{10}  + U_{1j})(Time_{ij})] + \varepsilon_{ij} $$
  

Understanding how to re-write the equation will help for calculating estimated scores for your predictors in addition to being able to interpret the coefficients.

For example, what would differ between the two equations for group coded = 0 versus a group = 1?


## Slope and Intercept effects

level 1: 
$$ {Y}_{ij} = \beta_{0j}  + \beta_{1j}Time_{ij} + \varepsilon_{ij} $$
Level 2: 
$$ {\beta}_{0j} = \gamma_{00} + \gamma_{01}G_{j} +   U_{0j}$$  
$$ {\beta}_{1j} = \gamma_{10} + \gamma_{11}G_{j} + U_{1j} $$  


Notice that when we combine Level 1 and Level 2, the intercept effects predictor becomes an interaction with time. This is called "cross level" interactions. Anytime you have a slope predictor that will be an interaction with time. I.e. we are asking does group status differ in their trajectory across time. One of these is a level 2 predictor and one is a level 1 predictor, thus a "cross level" interaction. 


Combined
  $$ {Y}_{ij} = \gamma_{00} + \gamma_{01}G_{j}+  \gamma_{10} (Time_{ij}) + \gamma_{11}(G_{j}*Time_{ij}) +  U_{0j} + U_{1j}(Time_{ij}) + \varepsilon_{ij} $$

$$ \begin{pmatrix} {U}_{0j} \\ {U}_{1j} \end{pmatrix}
\sim \mathcal{N} \begin{pmatrix} 
  0,     & \tau_{00}^{2} & \tau_{01}\\ 
  0, & \tau_{01} & \tau_{10}^{2}
\end{pmatrix} $$


$$ {R}_{ij} \sim \mathcal{N}(0, \sigma^{2})  $$


Alternative combined
$$ {Y}_{ij} = [\gamma_{00} + U_{0j} +\gamma_{01}G_{j}] + [(\gamma_{10}  + \gamma_{11}G_{j}+  U_{1j})(Time_{ij})] + \varepsilon_{ij} $$
  
### Equations necessary for plotting

The above equation can be simplified to get rid of the random effects to focus only on fixed effects portion. This is what you would use to get an estimated trajectory. 
  
  $$ \hat{Y}_{ij} = [\gamma_{00} +\gamma_{01}G_{j}] + [(\gamma_{10}  + \gamma_{11}G_{j})(Time_{ij})] $$
  
## Need for thinking about scaling your predictors

Redux of how to interpret lower order terms in an interaction regression model. Changing the scale of your predictors changes the interpretation of your model. We already saw this with the intercept and how we scaled time. Things will be the same here but more so as you can see in the alternative combined equation.

The intercept is always interpretted when the predictors are at zero. How can we interpret  $\beta_{0j}$ if there is a level 1 predictor? 

The same logic applies for $\beta_{1j}$ in that one would want the fixed parameters to represent the average effect. 

How to center? You dont want to necessarily overweight people with more time points, so you should do centering in the wide format unless people have the same number of assessment points. 


## Time-varying covariates (TVCs)

These are predictors that are assessed at level 1, which repeate. Note that there are some variables that are inherently level 2 (e.g. handedness), some that make sense more as a level 1 (e.g., mood) and some that could be considered either depending on your research question and/or your data (e.g. income). The latter type could concievably change across time (And thus be appropriate for a level 1 variable; tvc) but may not change at the rate of your construct or not be important.

We will go into these in more depth in further weeks. The two points I want to discuss now are: 

1. These can be treated as another predictor with the effect of "controlling" for some TVC. Thus the regression coefficents in the model are conditional on this covariate. 

For example, if you had group status (yes, no) as your TVC the fixed effect for this would indicate the difference in slope for the two conditions. The slope coefficient would be that average slope (depending on how the covariate is scaled)


2. The level 1 and level 2 models are not that different from previous forms. Here is an example model with a TVC. 

level 1: 
$$ {Y}_{ij} = \beta_{0j}  + \beta_{1j}Time_{ij} + \beta_{2j}Job_{ij} +\varepsilon_{ij} $$
Level 2: 
$$ {\beta}_{0j} = \gamma_{00} +    U_{0j}$$  
$$ {\beta}_{1j} = \gamma_{10} + U_{1j} $$
$$ {\beta}_{2j} = \gamma_{20} $$

3. It is not necessary to specify a random effect for the TVC. Doing so would suggest that the differences in group membership within a person is not the same across people. For example, the effect of jobloss may effect some peoples development but not others. 

The key question is whether or not we think the variability across people in their TVC effects are systematic or not. If they are systematic, then maybe it is important to predict them by another variable. Can we go further and also fit a random effects term? This is a tricky issue in that this adds an additional parameter to the random effects and thus increases the number of covariances estimated. Often our data are not large enough to estimate the increased number of parameters and results in non-convergence.

4. The introduction of the TVC can reduce $\tau^2_{U_{0j}}$, $\tau^2_{U_{1j}}$ and $\varepsilon_{ij}$. Normal time-invariant covariates only reduce the between person variance in intercept and slope and cannot account for the within person variance. 

But, but, because you are adding a new variable that changes the interpretation of the gamma terms, you may actually get increases in your variance components. As a result, it is difficult to directly compare models that have TVCs and those that do not. 

5. You may need to seperate between person and within person effects for TVC. This is done through various centering techniques. 


## Now you try

1. Run a series of models using a time-invariant nominal covariate. a) where the covariate only predicts the intercept b) predicts both intercept and slope c) is rescaled eg centering. For all models, how does your model change from model to model. What is your final model?  

2. Introduce a time-invariant continuous covariate and run models a-c from #1. 

3. Graph both of your final models for the continuous and nominal models above. 
4. Calculate confidence intervals around your estimates for your final models

5. Include both types of covariates in a single model. How does your interpretation of parameters change? 

6. If you have one available, introduce a time-varying covariate. 

