#lcmm

## latent class / mixture models

Thus far we have been assuming that people are all coming from a single population, that change paremeters are normally distributed, and that people can differ from the normative trend conitnuously. But what if this wasn't so? What if we were sampling people from different populations, that these different groups had different trajectories and that the variation in trajectories were explained by these groups? 

We can do this through something called latent class mixture models (among other names for a collection of these procedures). What they? Basically HLM + SEM + EFA/cluster analysis so as to "carve nature at its joints". More seriously, this is a procedure that is not unlike what we have been doing where we estimate growth trajectories. From there we are going to see if groups differ in their trajectories. But unlike before when we had groups entered in as covariates or through a multiple group model, we rely on the model to find the groups. That is, we do not have a group variable in our dataset. Instead we are asking to find different "classes" of trajectories (e.g., one group starts high and stays flat, another group starts low and increases). 

These are are thought to identify qualtitative differences in the way people change and develop over time. In one sense it makes it easier to understand the trajetories. Instead of people varying continuously where no one has the same trajectory and everyone is unique you can simplify to these smaller numeber of groups. Awesome! 

## Longitudinal Mixture models and Latent Class growth models-- what is the difference? 

Much like hlm, mlm, mixed models etcetera, there are a number of names to refer to these types of models. 

Basically, mixtures suggest that people have variability within a class whereas latent class would state that any variability within a class is noise and thus fix the variability to zero. That is, everything within a class/group is exactly the same. 

Other names get thrown around for these procedures, complicating interpretation e.g., latent profile analysis. Some of the differenes in terminology are the result of whether your measured variables are categorical vs continuous. But in broad strokes they all attempt to find groups based on the data. 





